package com.juaracoding.pcmspringbootcsr.constant;

public class ConstantMessageDivisi {

    public final static String WARNING_DIVISI_NOT_EXISTS = "DIVISI TIDAK DITEMUKAN";
    public final static String ERROR_NAMA_DIVISI_IS_NULL = "FIELD NAMA DIVISI TIDAK BOLEH NULL";
    public final static String ERROR_NAMA_DIVISI_IS_BLANK = "FIELD NAMA DIVISI TIDAK BOLEH DIISI SPASI SAJA";
    public final static String ERROR_NAMA_DIVISI_IS_EMPTY = "FIELD NAMA DIVISI TIDAK BOLEH KOSONG";
    public final static String ERROR_NAMA_DIVISI_LENGTH = "MINIMAL 5 MAKSIMAL 25 KARAKTER ";
    public final static String ERROR_KODE_DIVISI_IS_NULL = "FIELD KODE DIVISI TIDAK BOLEH NULL";
    public final static String ERROR_KODE_DIVISI_IS_BLANK = "FIELD KODE DIVISI TIDAK BOLEH DIISI SPASI SAJA";
    public final static String ERROR_KODE_DIVISI_IS_EMPTY = "FIELD KODE DIVISI TIDAK BOLEH KOSONG";
    public final static String ERROR_KODE_DIVISI_LENGTH = "MINIMAL 3 MAKSIMAL 5 KARAKTER ";
    public final static String ERROR_DESKRIPSI_DIVISI_IS_NULL = "FIELD DESKRIPSI DIVISI TIDAK BOLEH NULL";
    public final static String ERROR_DESKRIPSI_DIVISI_IS_BLANK = "FIELD DESKRIPSI DIVISI TIDAK BOLEH DIISI SPASI SAJA";
    public final static String ERROR_DESKRIPSI_DIVISI_IS_EMPTY = "FIELD DESKRIPSI DIVISI TIDAK BOLEH KOSONG";
    public final static String ERROR_DESKRIPSI_DIVISI_LENGTH = "MINIMAL 15 MAKSIMAL 55 KARAKTER ";


}
